# Either clone the content repositories listed under sources or delete the respective blocks.
# Clone the UI repository from plenty-docs-ui.
# Change USER in the url paths to your user name.
# To use the api-doc repository, update the page-specurl paths in /api-doc/plentymarkets/docs/modules/ROOT/pages/index.adoc and /api-doc/plentyBase/docs/modules/ROOT/pages/index.adoc, so that they point to valid files.
site:
  title: Developers documentation
  start_page: developers::homepage.adoc
  url: https://developers.plentymarkets.com/en-gb
content:
  sources:
    - url: ./
      branches: HEAD
      start_path: docs/en-gb
    - url: ./sources/api-doc
      branches:
        - HEAD
      start_path: plentymarkets/docs
    - url: ./sources/docs-raw
      branches:
        - HEAD
    - url: ./sources/Ceres_docs-raw
      branches:
        - HEAD
    - url: ./sources/IO_docs-raw
      branches:
        - HEAD
    - url: https://github.com/plentymarkets/plentyDevTool
      branches:
        - HEAD
      start_path: docs
asciidoc:
  attributes:
    tabs: tabs
  extensions:
    - ./lib/tabs-block.js
output:
  dir: ./build/en-gb
ui:
  bundle:
    url: ./sources/plenty-developers-docs-ui/build/ui-bundle.zip
    snapshot: true
