site:
  title: Developers documentation
  start_page: developers::homepage.adoc
  url: https://developers.plentymarkets.com/en-gb
content:
  sources:
  - url: ./
    branches: HEAD
    start_path: docs/en-gb
asciidoc:
  attributes:
    tabs: tabs
    icon: icon
  extensions:
  - ./lib/tabs-block.js
  - ./lib/inline-icon.js
output:
    dir: ./build/en-gb
ui:
  bundle:
    url: https://github.com/plentymarkets/plenty-docs-ui/raw/main/build/ui-bundle.zip
    snapshot: true
