= How to work with result converters

This how-to guide will introduce you to the usage of result converters in your catalogue.

== What are result converters?

Result converters are classes you can register in your template, which the catalogue will use in order to convert the export result according to your specifications. That way, the customer will be provided with a readable and ready-to-import file.

You can also use these converters to send the data to the marketplace, combining the conversion of the download data and the marketplace data in a single converter.

== Creating result converters

To create a result converter from scratch, all you need to do is to extend the BaseResultConverter class and to define your own:

- method: convertToDownload
- method: convertToMarketplace
- const: CHUNK_SIZE, defaults to 50
- const: MIME_TYPE, defaults to “text/plain”
- const: FILE_EXTENSION, defaults to “txt"

Example:
We will partially use the default CSV converter as an example.

.result-converters.php
[source,php]
----
include::example$result-converters.php[]
----

== Using defaults

We provide defaults for some formats that you can extend, where you will only need to define your own `convertToMarketplace` method.
If you need to customise the defaults you can override the `convertToDownload` method.

`namespace Plenty\Modules\Catalog\Services\Converter\ResultConverters\Defaults`

- CSV: CSVResultConverter
- JSON: JSONResultConverter
- TXT: TXTResultConverter
- XML: XMLResultConverter

== Using result converters

We set up the converter in order to store the export for the customer or to send it to the marketplace. However, we also need to provide it with the information, which data we need to export.

To do that you can feed the converter with any of the following source types:

- CatalogExportResult - returned by CatalogExportService's `getResult` method
- JSONL resource - returned by a cached result [ link to this documentation soon ]
- Collection
- LazyCollection [not available in plugins]
- CatalogLazyCollection - wrapper for LazyCollection with limited capabilities
- array

Example:
.source-types.php
[source,php]
----
include::example$source-types.php[]
----

If your converter requires any settings, you can pass them as an array to the `setSettings` method as shown below:

.converter-settings.php
[source,php]
----
include::example$converter-settings.php[]
----

You can also use a cached result to feed data to your converter:

.cached-result.php
[source,php]
----
include::example$cached-result.php[]
----

Internally, we have a very similar approach for exports that have been converted to a user's download.

== Registering your result converter in your template

In your template, you can register result converters as shown below:

.register-converter.php
[source,php]
----
include::example$register-converter.php[]
----
