= How to work with result converters

This how-to guide will introduce you to the usage of *result converters* in your catalogue.

== What are result converters?

Result converters are classes you can register in your template, which the catalogue will use in order to convert the export result according to your specifications. That way, the customer will be provided with a readable and ready-to-import file.

You can also use these converters to send the data to the marketplace, combining the conversion of the download data and the marketplace data in a single converter.

== Creating result converters

To create a result converter from scratch, all you need to do is to extend the xref:stable7@interface::Catalog.adoc#catalog_resultconverters_baseresultconverter[BaseResultConverter] class and to define your own:

* method: `convertToDownload`
* method: `convertToMarketplace`
* method: `getKey`
* method: `getLabel`
* const: *CHUNK_SIZE*, defaults to _50_
* const: *MIME_TYPE*, defaults to _text/plain_
* const: *FILE_EXTENSION*, defaults to _txt_

_Example_: +
We will partially use the default CSV converter as an example.

.result-converters.php
[source,php]
----
include::example$result-converters.php[]
----

== Using defaults

We provide defaults for some formats that you can extend, where you will only need to define your own `convertToMarketplace` method.
If you need to customise the defaults you can override the `convertToDownload` method.

`namespace Plenty\Modules\Catalog\Services\Converter\ResultConverters\Defaults`

* CSV: xref:stable7@interface::Catalog.adoc#catalog_defaults_csvresultconverter[CSVResultConverter]
* JSON: xref:stable7@interface::Catalog.adoc#catalog_defaults_jsonresultconverter[JSONResultConverter]
* TXT: xref:stable7@interface::Catalog.adoc#catalog_defaults_txtresultconverter[TXTResultConverter]
* XML: xref:stable7@interface::Catalog.adoc#catalog_defaults_xmlresultconverter[XMLResultConverter]

== Using result converters

We set up the converter in order to store the export for the customer or to send it to the marketplace. However, we also need to provide it with the information which data we need to export.

To do that you can feed the converter with any of the following source types:

* *CatalogExportResult*: returned by CatalogExportService's `getResult` method
* *JSONL resource*: returned by a cached result
* *Collection*

You can get your result converter directly from the template.

_Example_: +
.source-types.php
[source,php]
----
include::example$source-types.php[]
----

If, for some reason you can't access your template from the current scope, just instantiate your converter manually.

_Example_: +
.source-types-without-template.php
[source,php]
----
include::example$source-types-without-template.php[]
----

If your converter requires any settings, you can pass them as an array to the `setSettings` method as shown below:

.converter-settings.php
[source,php]
----
include::example$converter-settings.php[]
----

You can also use a cached result to feed data to your converter:

.cached-result.php
[source,php]
----
include::example$cached-result.php[]
----

== Registering your result converters in your template

In your template, you can register result converters as shown below. Note that you can exchange `ResultConverterContainer` for `DefaultResultConverterContainer` to enable all predefined converters in your template.

.register-converter.php
[source,php]
----
include::example$register-converter.php[]
----

Once you have registered your result converters, the user can select them in the *Format* drop-down list in the catalogue settings and the catalogue module will be able to build the file for the user using your specifications in the `convertToDownload` method.
