= Order search

This tutorial will show you how to search for orders using the route `GET /rest/orders/search`.

[NOTE]
====
The route `/rest/orders/search` can be called with the filters given in the request body, as will be shown in this tutorial. Since for some clients it is not possible to send request data in the body when using `GET`, the route can also be called with `POST`.
====

The filters can be given either as query string parameters ("simple filters") or in the request body ("complex filters"). Sending the filters in the request body is more complex but gives you more possibilities to filter and to combine filters.

To see which filters are available, refer to the https://developers.plentymarkets.com/en-gb/plentymarkets-rest-api/index.html#/Order/get_rest_orders_search[REST documentation].

== Simple filters

When searching by using the simple filters, the filters are given as query string parameters. The shown operators are available only for filters for which they make sense. For example, it is not possible to filter for a range for a string filter.

=== Search for single value

To search for a single values, the filters can just be defined like this:

```
GET /rest/orders/search?orderTypeId=1&statusId=3
```

This filters all sales orders (`orderTypeId = 1`) in the status 3.

This notation is equivalent to the example above:

```
GET /rest/orders/search?orderTypeId=eq:1&statusId=eq:3
```

=== Search for multiple values

This is an example how to filter all orders in the status 3 or 4:

```
GET /rest/orders/search?statusId=in:3,4
```

=== Search for ranges

To filter for a range of values, these operators are availabe:

- `lt`: less than
- `lte`: less than equal
- `gt`: greater than
- `gte`: greater than equal
- `between`: values between the given values, bounds are inclusive

This is an example how to filter all orders with a status less than 7:

```
GET /rest/orders/search?statusId=lt:7
```

And this example filters all orders that were created between the dates `2021-12-22T00:00:00+01:00` and `2021-12-22T23:59:59+01:00`:

```
GET /rest/orders/search?createdAt=between:2021-12-22T00%3A00%3A00%2B01%3A00,2021-12-22T23%3A59%3A59%2B01%3A00
```

[NOTE]
====
Data given as query string parameters must be URL encoded. So in this example the string `2021-12-22T00:00:00+01:00` must be encoded as `2021-12-22T00%3A00%3A00%2B01%3A00`. This is not necessary when sending the filters in the request body.
====

=== Search with logical operators

To filter for example all orders that are not in the status 3, use the `not` operator:

```
GET /rest/orders/search?statusId=not:3
```

It is possible to combine filters for the same field with logical AND or OR operators.

Filter all orders that have a status greater 3 and less than 5:

```
GET /rest/orders/search?statusId=gt:3+AND+lt:5
```

Filter all orders that have the status 3 or a status greater than 6:

```
GET /rest/orders/search?statusId=eq:3+OR+gt:6
```

== Complex filters

Complex filters are given in the request body in the JSON format. This is an example how to filter all orders with the status 3:

.GET /rest/orders/search
[source,json]
----
{
    "conditionType": "and",
    "fields": [
        {
            "field": "statusId",
            "operator": "eq",
            "value": 3
        }
    ],
    "groups": []
}
----

The complex filters are defined a "group" whereby each group can contain other groups. A group consist of these fields:

- `conditionType`: The logical operator that defines how the values in `fields` and `groups` should be combined. Possible values are `and` and `or`.
- `fields`: An array of the filters.
- `groups`: An array of nested groups.

Each value of the `fields` array consists of these fields:

- `field`: The name of the order filter as defined in the REST documentation.
- `operator`: Defines how to filter.
- `value`: The value to filter for. Can be a single value, an array or null (depending on the operator).

These are the possible operators:

- `eq`: The value must be equal to the given value
- `not`: The value must not be equal the given value
- `in`: The value must be present in the given array
- `nin`: The value must not be present in the given array
- `null`: The value must not be existing
- `nn`: The value must exist
- `lt`: The value must be less than the given value
- `lte`: The value must be less than equal the given value
- `gt`: The value must be greater than the given value
- `gte`: The value must be greater than equal the given value
- `between`: The value must be between the two given values

=== Combine filters

This example filters all orders that are sales orders and that have a status between 3 and 5. Both filters must apply because `conditionType = and`.

.GET /rest/orders/search
[source,json]
----
{
    "conditionType": "and",
    "fields": [
        {
            "field": "orderTypeId",
            "operator": "eq",
            "value": 1
        },
        {
            "field": "statusId",
            "operator": "between",
            "value": [3, 5]
        }
    ],
    "groups": []
}
----

The following example filters all orders where there is an order item present with either variation ID = 1001 or item ID = 107. Only one of the filters must apply because `conditionType = or`.

.GET /rest/orders/search
[source,json]
----
{
    "conditionType": "or",
    "fields": [
        {
            "field": "itemVariationId",
            "operator": "eq",
            "value": 1001
        },
        {
            "field": "itemId",
            "operator": "eq",
            "value": 107
        }
    ],
    "groups": []
}
----

=== Nested filters

For more complex conditions, the field `groups` can be used. The given groups are combined as defined in the `conditionType` of the parent group. Inside the given groups another `conditionType` can be used.

This example filters all orders that are sales orders, have the referrer ID 9 and have either a status less than equal 5 or equal 8.

.GET /rest/orders/search
[source,json]
----
{
    "conditionType": "and",
    "fields": [
        {
            "field": "orderTypeId",
            "operator": "eq",
            "value": 1
        },
        {
            "field": "referrerId",
            "operator": "eq",
            "value": 9
        }
    ],
    "groups": [
        {
            "conditionType": "or",
            "fields": [
                {
                    "field": "statusId",
                    "operator": "lte",
                    "value": 5
                },
                {
                    "field": "statusId",
                    "operator": "eq",
                    "value": 8
                }
            ],
            "groups": []
        }
    ]
}
----