= Vue Server-Side Rendering in Ceres

// Infos zur Versionsnummer ergänzen
With the next version of the Ceres plugin, we will introduce Vue Server-Side Rendering (SSR) to Ceres. 
This update serves to prepare Ceres online shops for the changes brought by the Google core update.

With SSR, Vue.js components, whose markup was previously generated in the browser, are now already processed on the web server.
Therefore, the HTML, that has already been generated, is sent to the browser and can directly be displayed there.
Consequently, the page can already be displayed before the necessary JavaScript has been loaded and interpreted.
Nevertheless, Vue.js applications that are rendered on the server side are also initialised and rendered again in the browser in order to subsequently equip the static markup delivered by the server with dynamic parts of a web application, such as click listeners, data bindings, etc.
The process of adding dynamic application parts to the static markup is called *hydration*.
For this, it is important that the markup provided by the server and the markup generated in the browser do not differ.

== Basics

The basis of the implementation of SSR in Ceres is the link:https://ssr.vuejs.org/[official SSR guide of Vue.js].

The section link:https://ssr.vuejs.org/guide/universal.html#data-reactivity-on-the-server[Writing Universal Code] defines some basic requirements that must be fulfilled by Vue components so they can be processed on the server side.
The implementation in Ceres also has the following requirements:

* Currently, only so-called Single-File-Components (SFCs) are rendered on the server side. In Ceres, this covers all components on static pages, category and item views. At this time, MyAccount, Checkout and associated pages, such as order confirmation, return form etc., can not be rendered on the server side.
* Individual templates that are referenced via the `override-template` property on a Vue component cannot be taken into account on the server side and therefore lead to hydration errors (see above). However, it is possible to explicitly exclude individual components from server-side rendering (see below).

The global overwriting of component templates through the `data-component` attribute on the corresponding script tag is still possible (see link:https://developers.plentymarkets.com/en-gb/developers/main/plentyshop-plugins/theme-plugins.html#_changing_the_template_of_a_vue_component[Changing the template of a Vue component]).

== Preparing a template for SSR

During server-side rendering, the browser-specific objects `window` and `document` and thus all common functions for browsing or manipulating the DOM are not available.
For this reason, the template must be provided with markers (so-called "directives") in some relevant places, on the basis of which the HTML document can be analysed and interpreted.
These are specified in the form of HTML comments in order to obtain valid HTML even without further processing. 
However, during processing by server-side rendering, these comments are removed and not delivered to the browser.

All directives start with an HTML template of the form `<!-- SSR:xyz() -\->` and end with another comment of the form `<!-- /SSR -\->`. Directives cannot be nested.

The following directives are available:

=== SSR:app() directive

This directive marks the element that should be used as the template for the main component. In Ceres, for example, this element is marked with the ID “vue-app”.

[source,twig]
----
<!-- SSR:app() -->
<div id="vue-app">
...
</div>
<!-- /SSR -->
----

This directive should only be used *once per page*.

=== SSR:global($identifier) directive
This directive marks a script tag with JSON-formatted data that needs to be globally available during server-side rendering under the specified identifier.

[source,twig]
----
<!-- SSR:global(App) -->
<script id="app-data" type="application/json">
    {
        "config": {{ ceresConfig | json_encode | raw }},
        "urls": {{ urls | json_encode | raw }}
    }
</script>
<!-- /SSR -->
----

Within server-side rendered components, the example above enables, for instance, the access to `App.config`.

=== SSR:entry($path) directive
This directive specifies the path to a JavaScript module that should be loaded during server-side rendering.
This directive is *not* closed by a comment of the form `<!-- /SSR -\->`!

To determine the correct path, the Twig function `ssr_entry()` should be used here:

[source,twig]
----
<!-- SSR:entry({{ ssr_entry('Ceres', 'path/to/bundle.js') }}) -->
----

See the section "Providing JavaScript modules for SSR" for more details and requirements for server-side loaded modules.

=== SSR:on() and SSR:off() directives
The content of the directive is only output when the SSR is active/inactive and removed otherwise.

[source,twig]
----
<!-- SSR:on() -->
<p>This page was rendered on the server-side!</p>
<!-- /SSR -->

<!-- SSR:off() -->
<p>This page was not rendered on the server-side!</p>
<!-- /SSR -->
----

=== SSR:template($componentTag) directive
To overwrite the template of a Vue component, the script tag with the corresponding `data-component` attribute must be marked by the directive `SSR:template`.

[source,twig]
----
<!-- SSR:template(add-to-basket) -->
<script type="x/template" data-component="add-to-basket">
...
</script>
<!-- /SSR -->
----

== Providing JavaScript modules for SSR

The directive  `<!-- SSR:entry() -->`  can be used to load arbitrary JavaScript modules during server-side rendering, e.g. to register own Vue components or to change the initial state of the VueX state.

Provided modules should be bundled as  **commonjs2**  modules (see [Webpack: output.libraryTarget ](https://webpack.js.org/configuration/output/#librarytarget-commonjs2) for further information). The following fields can be exported per module:

* **`beforeCreate: (context) => void`**  : Function that is executed before server-side creation of the Vue application and is passed the renderer context as an argument.
* **`beforeRender: (context) => void`**  : Function that is executed before server-side rendering and is passed the created instance of the Vue application as an argument.
* **`afterRender: (vueApp) => void`**  : Function that is executed after server-side rendering. It receives the created instance of the Vue application as an argument.
* **`globals: { [key: string]: any }`**  : Object whose values are made globally available with the respective key as variable name.
* **`createApp: (context) => Promise<Vue>`**  : Method that creates the actual Vue instance for the respective context. The implementation by previously loaded modules is overwritten.

[source,twig]
----
import Vue from "vue";
const globals = { Vue };

function beforeCreate(context) {
    ...
}

function beforeRender(vueApp) {
    ...
}

function afterRender(vueApp) {
    ...
}

export { globals, beforeCreate, beforeRender, afterRender };
----

## Switching Ceres to server-side rendering

The necessary changes to Ceres are currently available on GitHub on the branch "**feature/ssr**".
No adjustments are necessary for IO, meaning that the IO stable branch or the version from the Marketplace can be used.
To be able to use the SSR feature, test systems must currently be activated by us or moved to an appropriate test environment. 
Alternatively, you can order your own test systems with activated server-side rendering for the duration of the hackathon (until 30 April).
For more information see link:https://forum.plentymarkets.com/t/umstellung-von-entwicklersystemen-auf-ssr/630603[this post in the forum].

## Adding preloading to your widgets

In the context of Server-Side Rendering, we added the setting **Preload image** to our image widgets.
This setting allows that the images used in the widgets image box, image carousel, background image, and item image are already processed on the server's side, so that the shop's performance can be increased. You can find further information on how to best use preloading in our link:https://knowledge.plentymarkets.com/en/online-store/best-practices#psi[PageSpeed Insights best practice].

If you are creating your own widgets that use images, this section will help you learn how to include preloading in your widgets.

### Creating a setting in the widget PHP class

First, you should extend the PHP class of your widget with a setting that the user can activate and deactivate. Our image 
box widget uses a common checkbox for this:

[source,PHP]
----
$settings->createCheckbox('preloadImage')
            ->withName('Widget.preloadImageLabel')
            ->withTooltip('Widget.preloadImageTooltip')
            ->withCondition("!lazyLoading");
            
----

Note that the image box widget can only be preloaded if lazy loading is not active. 
The setting includes all the usual suspects: the interactive element, the title, and the tooltip.

### Implementing Twig code

After you've added the setting to the PHP class, it is time to add the relevant Twig code to the widget.
First, make sure to access the settings you just added:

[source,twig]
----
{% set preloadImage     = widget.settings.preloadImage.mobile %}
----

In a next step, it is important that you set the URL of the image with `Twig.set` in the Twig builder because you will need the image URL in the subsequent step.

[source,twig]
----
{{ Twig.set("imageUrl", "" | json_encode) }}
----

Finally, add a conditional if construction and use `Twig.print` to hand over the image URL you set before.
While most image formats are automatically recognized as the **image type** (namely PNG, JPG, JPEG, WEBP, and GIF), you should still include `'image'` in case another format is used.

[source,twig]
----
{% if preloadImage %}
    {{ Twig.print("add_asset(imageUrl,'image')") }}
{% endif %}
----

And that's it. 
If you would like to take a look at how team plentyShop implemented preloading in their widgets, feel free to check out the open source code of the link:https://github.com/plentymarkets/plugin-ceres/pull/2802/files#diff-bd9967b42e5604fbd1cc0034b2ed9fbc4bb18113880fe371167076f046aee956[background image widget], link:https://github.com/plentymarkets/plugin-ceres/pull/2802/files#diff-9f438954b9f177761379a8b382eea014077ec743060583796ac4f9aaed3d3003[image box widget] (which was used as the basis of this guide), or the link:https://github.com/plentymarkets/plugin-ceres/pull/2802/files#diff-43b0576fe9cb61d0343a4aa220f562347c237717821f276ab632973e3970ec96[image carousel widget].