= Template setup

When developing your own plugin to extend your online store, you may want to use the default plentymarkets design as a starting point. It is comprised of two plugins:

* https://github.com/plentymarkets/plugin-ceres[plentyShop LTS]
* https://github.com/plentymarkets/plugin-io[IO]

By including them via Git, you can modify them according to your needs. This page describes how to add plentyShop LTS and IO from GitHub to your plentymarkets system and the existing branches.

== Adding plentyShop LTS and IO to your system

. Open the back end of your plentymarkets system.
. Go to *Plugins » Git*.
. Click on Add new Repository. +
icon:arrow-right[] The repository settings are displayed.
. Enter the https://github.com/plentymarkets/plugin-ceres[plentyShop LTS repository URL] as well as _any_ user name and token into the respective fields.
. Change the branch you want to check our during installation to either *stable* or *beta*. See below for more information on the various branches.
. *Save* the settings. +
icon:arrow-right[] plentymarkets checks and establishes the connection to the Git repository.

Repeat the above steps for the https://github.com/plentymarkets/plugin-io[IO plugin]. Once you have added both plugins, install them in a plugin set:

. Go to *Plugins » Plugin overview*.
. Select the plugin set you want to work in or create a new one via the *Create new set* button.
. Filter for uninstalled plugins, then install the newly added plentyShop LTS and IO plugins one after the other. +
*NOTE* that you cannot install these plugins if you have already installed the Marketplace versions in the same set.
. Change the *Position* of the plugins, so that IO has the highest value and plentyShop LTS the second highest.
. Click on *Save & publish plugin set*.

== plentyShop LTS release cycle

Two branches of the plentyShop LTS and IO repositories are important to describe the release cycle of the design: *Development*, *Beta* and *Stable*.

[cols="1,3"]
|===
|Branch |Description

|*Beta*
|The *Beta* branch is the main branch for plentymarkets 7 systems in beta status. It is recommended to use the *Beta* branches of our repositories for a beta system. The *Stable* branches will also work with beta systems, but certain features or fixes released when *Development* branches are merged into the *Beta* branches are not available in *Stable* branches yet. The *Beta* branches will be merged into *Stable* approx. every 2 weeks and the new *Stable* branches will be released.

|*Stable*
|The *Stable* branch are the main branch for plentymarkets 7 systems in stable status. It is recommended to use the *Stable* branches of our repositories for a stable system. The *Beta* branches will not necessarily work with stable systems. It is possible that certain menus or features of plentymarkets do not work if you check out and use *Beta* branches in a stable system. Approx. every 2 weeks, the new *Stable* branches will be released.

|*Other branches*
|Other branches of our repositories are work-in-progress branches of plentymarkets developers. It is not recommended to use these branches in a beta or stable system.
|===
