= Angular back end UI

This page provides information about a back end UI and its components. All plentymarkets UIs are Angular UIs. Angular is a Javascript framework for creating web, desktop and mobile applications. Developing Angular applications involves the usage of Typescript along with HTML, CSS etc. Such applications are built by components, which define different areas in the UI that let you use specific UI functionalities. If you are not familiar with Angular yet and want to find out more, see the Angular documentation: https://angular.io.

== Back end menu information

All information about the back end menu entries is saved in a ui.json file. This file defines the entry points for the plugin. Views are then available at the respective menus.

This could look like the following:

.ui.json
[source,json]
----
include::example$ui.json[]
----

== Plugin menu entries

The following section lists the specific properties of your plugin's menu entries.

=== defaultEntryPoint

The default entry point of your plugin

=== namespace

The namespace of your plugin

=== menuEntries

The menu entries of your plugin. +
The following information is saved for a menu entry:

* `label`: The label to be displayed in the back end +
* `menu`: The menu that can be accessed by a plugin via entry points.
<a href="/terra-doc/routes" target="_blank">Click here</a> for a list of possible menu entry points. +
* `urlKey`: The route for the view in our plentymarkets back end, e.g.                         http://your-plentystore.co.uk/plenty/ui-backend/start/hello-world +
*_Note:_* For the URL key of the plugin, only use hyphens. +
* `entryPoint`: The entry point of your plugin +
* `icon`: The icon for the menu entry in the system tree. If no icon is specified, the standard plugin icon is displayed. To not display any icon, use "icon": "none". Find a list of all icons <a href="/terra-doc/icons">here.</a>

== Integrating plugins into the back end

It is possible to seamlessly integrate your plugin into the plentymarkets back end. You can use entry points to add your plugin to the top navigation bar or routes to add it to the navigation tree of the *Setup* menu.

=== Menu entry points

Back end views can be integrated in the plentymarkets main menu. A list of all menus that can be accessed by a plugin via entry points can be found on this page: LINK to reference page.

=== Routes in the system tree

The Terra system tree offers plugin developers the opportunity to register their plugin behind a route. In doing so, the plugin becomes accessible in the system tree like a regular part of Terra. You can read about the different points of entry in the table below. Find an instruction how to register your plugin <a href="/tutorials/backendview#code-uijson">here.</a>

A list of all available routes that can be accessed by plugins can be found here: LINK. +

icon:warning[role="red"] [red]#Required# +
Note that all routes need an introducing `system`. Older routes beginning with `settings` will be mapped to match the new format.
Since the new menu item for the system tree was renamed to 'Setup', the new full system tree path also starts with 'Setup'.

=== Plugin positioning

In addition to inserting plugins as desired in menus under *Setup*, it is now also possible to determine their position depending on their route.
If using a route not mentioned in this list (insert LINK), a parent node is created with the specified name. It appears underneath the actual entry.
In case of several entries whose last part of the route is identical, they are all inserted underneath this part of the route. Thus, only the position of the first entry is considered.
