= Github webhooks

Github webhooks let you set up webhooks to your Github repositories, allowing you to automatically update and deploy your plugins from your plentymarkets inbox.

== Setup

Go to https://github.com/settings/tokens[Github] and create a new personal access token. This token is used for authenticating your Github account in plentymarkets.

. Go to https://github.com/settings/tokens.
. Click on *Generate new token*.
. Enter a *Note*, e.g. the plugin name.
. Under *Select scopes*, activate *repo* to access the commit
status. +
→ The status is required to inform you about successful or failed
deployment of plugins.
. Click on *Generate token*. +
→ The personal access token will be generated.
. Click on *Copy token* to copy the token to the clipboard. +
→ In the plentymarkets back end, this token will be used instead of your Github password.

== Back end configuration

Open your plentymarkets back end and add your Git plugin to your system.

. Go to *Plugins » Git*.
. Click on *New plugin*. +
→ The *Settings* window will open.
. Enter the remote URL of your Github repository.
. Enter your Github user name.
. Paste the copied personal access token into the *Password* field.
. Enter the name of an existing branch of the repository you want to clone.
. *Save* the settings. +
→ The plugin repository is copied to the plentymarkets inbox.
. Copy the *Webhook Token* to the clipboard.

== Github configuration

Go to your Github repository and set up a new webhook for the repository.

. Go to link:https://github.com[Github^].
. Under *Your repositories*, click on the plugin repository. +
→ The *Code* tab will open.
. Click on the *Settings* tab.
. Click on *Webhooks*.
. Click on *Add webhook*.
. Enter the *Payload URL*. The payload URL consists of the online store URL of your standard client and `+/rest/plugins/hook+`, e.g. `+https://www.your-plentystore.co.uk/rest/plugins/hook+`.
. Select *application/json* from the *Content type* drop-down menu.
. Paste the webhook token from the plentymarkets back end into the *Secret* field. +
→ This token is used for securing the communication between Github and plentymarkets.
. *Disable* SSL verification.
. For *Which events would you like to trigger this webhook?*, select *Just the push event.*
. Click on *Add webhook*. +
→ The webhook will be displayed under *Webhooks*.

== Usage

When making changes to your Github repository and committing the changes, your plugin will be updated and deployed automatically via the webhook. Changes will be visible shortly after the commit. You can check whether or not the commit was deployed successfully by following these steps:

. Go to https://github.com[Github].
. Under *Your repositories*, click on the plugin repository. +
→ The *Code* tab will open.
. In the list of *Commits*, the commit is flagged *Pending* while deploying the plugin. +
→ After a short while, *Pending* will change to *Success* if updating and deploying was successful or to *Failure* if the deployment failed.
